## Colors configuration
[colors.primary]
background = "#11111b"
foreground = "#ABB2BF"

[colors.normal]
black   = "#32363D"
red     = "#E06B74"
green   = "#98C379"
yellow  = "#E5C07A"
blue    = "#62AEEF"
magenta = "#C778DD"
cyan    = "#55B6C2"
white   = "#ABB2BF"

[colors.bright]
black   = "#50545B"
red     = "#EA757E"
green   = "#A2CD83"
yellow  = "#EFCA84"
blue    = "#6CB8F9"
magenta = "#D282E7"
cyan    = "#5FC0CC"
white   = "#B5BCC9"
